version: 2.1

orbs:
  swiftlint: ngs/swiftlint@0.0.1
  fastlane: ngs/fastlane@0.0.2

commands:
  setup:
    steps:
      - checkout
      - fastlane/bundle-install
  pod_setup:
    steps:
      - restore_cache:
          keys:
            - v1-pods-{{ checksum "Podfile.lock" }}
      - run:
            name: pod install
            working_directory: Pods
            command: |
              curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
              bundle exec pod install
      - save_cache:
          key: v1-pods-{{ checksum "Podfile.lock" }}
          paths:
            - Pods

jobs:
  build:
    executor: fastlane/macos
    parameters:
      target:
        type: enum
        enum: [beta, release]
    steps:
      - setup
      - pod_setup

workflows:
  app:
    jobs:
      - build:
          name: beta_build
          target: beta
          filters:
            branches:
              only: [master, develop_ci]
